# SITE SETTINGS
title: voidstar
author: Brett Vickers
description: >
  Computers. Code. A few other things.
url: "https://beevik.github.io/"
baseurl: "/voidstar"
imageurl: "/voidstar/assets/img/posts"

# SEO PLUGIN
social:
  name: Brett Vickers
  links:
    - https://github.com/beevik
    - https://twitter.com/beevik

# THEME SETTINGS
navigation:
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Computers. Code. A few other things.

hero_img: voidstar.jpg

email: your-email@domain.com

twitter_username: beevik
github_username:  beevik

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

sass:
  sass_dir: _sass
  style: compressed

service_worker: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
